---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: profilarr
  name: profilarr
  namespace: multimedia-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profilarr
  template:
    metadata:
      labels:
        app: profilarr
    spec:
      containers:
      - name: profilarr
        image: santiagosayshey/profilarr:latest
        ports:
        - containerPort: 9696
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: UMASK
          value: '002'
        - name: TZ
          value: Etc/UTC
        volumeMounts:
        - mountPath: /config
          name: profilarr-config
      volumes:
      - name: profilarr-config
        persistentVolumeClaim:
          claimName: profilarr-config
