apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: extra-tools
spec:
  type: ClusterIP
  selector:
    app: filebrowser
  ports:
    - name: filebrowser
      port: 80
      targetPort: 80
      protocol: TCP
