---
apiVersion: v1
kind: Service
metadata:
  name: fileflows-node
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: fileflows-node
  ports:
  - name: fileflows-node
    port: 5000
    targetPort: 5000
    protocol: TCP
