---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-server
  namespace: extra-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-spotify-server
  template:
    metadata:
      labels:
        app: your-spotify-server
    spec:
      containers:
      - name: server
        image: yooooomi/your_spotify_server
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: spotify-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-web
  namespace: extra-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-spotify-web
  template:
    metadata:
      labels:
        app: your-spotify-web
    spec:
      containers:
      - name: web
        image: yooooomi/your_spotify_client
        ports:
        - containerPort: 3000
        env:
        - name: API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: spotify-secret
              key: API_ENDPOINT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: extra-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: spotify-mongo