---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-server
  namespace: extra-tools
spec:
  selector:
    app: your-spotify-server
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-web
  namespace: extra-tools
spec:
  selector:
    app: your-spotify-web
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: extra-tools
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP