---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: seerr
  ports:
  - name: seerr
    port: 5055
    targetPort: 5055
    protocol: TCP
