apiVersion: v1
kind: Service
metadata:
  name: animeworld
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: animeworld
  ports:
    - name: animeworld
      port: 5000
      targetPort: 5000
      protocol: TCP
