apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: multimedia-factory
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: DOCKER_MODS
          value: "ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest"
        ports:
        - containerPort: 8080
          name: webui
        - containerPort: 31682
          name: torrent-tcp
          protocol: TCP
        - containerPort: 31682
          name: torrent-udp
          protocol: UDP
        volumeMounts:
        - mountPath: /config
          name: qbittorrent-config
        - mountPath: /data
          name: qbittorrent-data
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      # initContainers:
      # - name: gluetun
      #   image: ghcr.io/qdm12/gluetun:v3.41.0
      #   securityContext:
      #     capabilities:
      #       add: ["NET_ADMIN"]
      #   ports:
      #     - name: http
      #       containerPort: 8080
      #       protocol: TCP
      #   envFrom:
      #     - secretRef:
      #         name: gluetun-secret
      #   restartPolicy: Always
      #   readinessProbe:
      #     exec:
      #       command:
      #         - sh
      #         - -c
      #         - "ping -c 1 $(echo $WIREGUARD_ADDRESSES | cut -d'/' -f1)"
      #     initialDelaySeconds: 5
      #     periodSeconds: 3
      #     timeoutSeconds: 2
      #     failureThreshold: 3
      #   livenessProbe:
      #     exec:
      #       command:
      #         - sh
      #         - -c
      #         - "ping -c 1 $(echo $WIREGUARD_ADDRESSES | cut -d'/' -f1)"
      #     initialDelaySeconds: 10
      #     periodSeconds: 15
      #     timeoutSeconds: 2
      #     failureThreshold: 3
      volumes:
      - name: qbittorrent-data
        persistentVolumeClaim:
          claimName: qbittorrent-data
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config
