---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: system-addon
spec:
  type: ClusterIP
  selector:
    app: cloudflared
  ports:
  - name: cloudflared
    port: 2000
    targetPort: 2000
    protocol: TCP
