---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: home-automation
spec:
  ports:
  - port: 8581
    protocol: TCP
    targetPort: 8581
  selector:
    app: homebridge
  type: ClusterIP
