---
apiVersion: v1
kind: Service
metadata:
  name: duplicati
  namespace: system-addon
spec:
  type: ClusterIP
  selector:
    app: duplicati
  ports:
  - name: duplicati
    port: 8200
    targetPort: 8200
    protocol: TCP
