---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: maintainerr
  ports:
  - name: maintainerr
    port: 6246
    targetPort: 6246
    protocol: TCP
