---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: bazarr
  ports:
  - name: bazarr
    port: 6767
    targetPort: 6767
    protocol: TCP
