---
apiVersion: v1
kind: Service
metadata:
  name: fileflows
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: fileflows
  ports:
  - name: fileflows
    port: 5000
    targetPort: 5000
    protocol: TCP
