---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: tautulli
  ports:
  - name: tautulli
    port: 8181
    targetPort: 8181
    protocol: TCP
