---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: multimedia-factory
spec:
  type: ClusterIP
  selector:
    app: jellyseerr
  ports:
  - name: jellyseerr
    port: 5055
    targetPort: 5055
    protocol: TCP
